# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      # Build for 1.21.8
      - name: "Stonecutter: set active to 1.21.8"
        run: ./gradlew stonecutterSwitchTo1.21.8 --no-daemon --stacktrace
      - name: Build 1.21.8
        run: ./gradlew :1.21.8:build --no-daemon --stacktrace
      - name: Upload artifact 1.21.8
        uses: actions/upload-artifact@v4
        with:
          name: 1.21.8
          path: "**/build/libs/*-1.21.8.jar"

      # Build for 1.21.10
      - name: "Stonecutter: set active to 1.21.10"
        run: ./gradlew stonecutterSwitchTo1.21.10 --no-daemon --stacktrace
      - name: Build 1.21.10
        run: ./gradlew :1.21.10:build --no-daemon --stacktrace
      - name: Upload artifact 1.21.10
        uses: actions/upload-artifact@v4
        with:
          name: 1.21.10
          path: "**/build/libs/*-1.21.10.jar"

      # Build for 1.21.11
      - name: "Stonecutter: set active to 1.21.11"
        run: ./gradlew stonecutterSwitchTo1.21.11 --no-daemon --stacktrace
      - name: Build 1.21.11
        run: ./gradlew :1.21.11:build --no-daemon --stacktrace
      - name: Upload artifact 1.21.11
        uses: actions/upload-artifact@v4
        with:
          name: 1.21.11
          path: "**/build/libs/*-1.21.11.jar"